image: rust:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy_production

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - ssh xum35s@ec2-3-123-3-198.eu-central-1.compute.amazonaws.com "cd /var/www/html/diazpons && git pull origin master"
    - ssh xum35s@ec2-3-123-3-198.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && source ~/.cargo/env && cd /var/www/html/diazpons && git checkout master && cargo build --release"
    - ssh xum35s@ec2-3-123-3-198.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && source ~/.cargo/env && cd /var/www/html/diazpons && cargo sweep -t 1"
    - ssh xum35s@ec2-3-123-3-198.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && source ~/.cargo/env && cd /var/www/html/diazpons && npm ci --verbose"
    - ssh xum35s@ec2-3-123-3-198.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && source ~/.cargo/env && cd /var/www/html/diazpons && npm run build::js"
    - ssh xum35s@ec2-3-123-3-198.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && source ~/.cargo/env && cd /var/www/html/diazpons && cargo build --release && pm2 stop diazpons --silent || true && pm2 delete diazpons --silent || true && pm2 start target/release/diazpons --name diazpons --update-env"
