image: rust:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq git openssh-client nodejs npm

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)

  - echo "$SERVER_KEY" | base64 -d > ~/.ssh/id_rsa_server
  - chmod 600 ~/.ssh/id_rsa_server
  - ssh-add ~/.ssh/id_rsa_server

  - echo "$GITHUB_KEY" | base64 -d > ~/.ssh/id_rsa_github
  - chmod 600 ~/.ssh/id_rsa_github
  - ssh-add ~/.ssh/id_rsa_github

  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

stages:
  - github_clone
  - deploy_production

github_clone:
  stage: github_clone
  variables:
    GIT_DEPTH: "0"
  script:
    - git checkout -B "$CI_COMMIT_REF_NAME"
    - git remote remove github || true
    - git remote add github "git@github.com:${GITHUB_ACCOUNT}/${GITHUB_PROJECT}.git"
    - git push github --all
    - git push github --tags

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
      cd ${SERVER_PROJECT_PATH}/${SERVER_SOURCE_CODE_FOLDER}
      && git checkout master
      && git pull origin master
      && export PORT_HTTP=${PORT_HTTP}
      && export IP=${IP}
      && docker compose -p ${PROJECT_NAME} -f docker-compose.base.yml -f docker-compose.prod.yml up -d --build
      "
