image: rust:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy_production

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH}
        && git add .
        && git stash
        && git stash clear
        && git pull origin master
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && source ~/.cargo/env
        && cd ${SERVER_PATH}
        && git checkout master
        && cargo build --release
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && source ~/.cargo/env
        && cd ${SERVER_PATH}
        && cargo sweep -t 1
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && source ~/.cargo/env
        && cd ${SERVER_PATH}
        && npm ci --verbose
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && source ~/.cargo/env
        && cd ${SERVER_PATH}
        && ENVIRONMENT=${ENVIRONMENT} npm run build::js
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && source ~/.cargo/env
        && cd ${SERVER_PATH}
        && export ENVIRONMENT=${ENVIRONMENT}
        && cargo build --release
        && pm2 stop diazpons --silent || true
        && pm2 delete diazpons --silent || true
        && pm2 start target/release/diazpons --name diazpons --update-env
      "
